In [1]:
import datetime
import numpy as np
import pandas as pd
import yfinance as yf
from math import sqrt
from pandas_datareader import data as pdr

In [2]:
df = pd.read_csv("stocksymbols - Sheet1.csv")
syms = list(df['Symbol'])
print(syms)

['SBIN.NS', 'AXISBANK.BO', 'IOC.BO', 'NMDC.BO', 'KRITIIND.BO', 'TATAPOWER.NS', 'AUROLAB.BO', 'RESONANCE.BO', 'ANDHRAPET.BO', 'MANALIPETC.BO', 'GAIL.NS', 'SAIL.NS', 'HDFCBANK.BO', 'ONGC.NS', 'INFY.BO', 'BHAGYAPROP.BO', 'FEDERALBNK.NS', 'WIPRO.BO', 'IDEA.NS', 'ALOKTEXT.BO', 'BANKBARODA.BO', 'BHEL.NS', 'DISHTV.BO', 'VEDL.BO', 'PTC.NS', 'PRESSMN.NS', 'VEDL.BO']


#### Monthly Average Return

In [3]:
ret = 0
start = "2016-04-01"
df = pdr.get_data_yahoo("SBIN.NS", start = "2016-04-01", end = "2019-04-01")
for i in range(36):
    end = start[:5]
    month = int(start[5:7]) + 1
    if month <= 9:
        end += '0' + str(month) + start[7:]
    elif month > 12:
        end = str(int(start[:4]) + 1) + '-01-01'
    else:
        end += str(month) + start[7:]
    sliced_data = df.loc[(df.index >= start) & (df.index <= end)]
    #df = pdr.get_data_yahoo("SBIN.NS", start = start, end = end)
    ret += (sliced_data.iloc[-1]['Close'] - sliced_data.iloc[0]['Open']) / 36
    print(i, start, end)
    start = end
print(ret)

0 2016-04-01 2016-05-01
1 2016-05-01 2016-06-01
2 2016-06-01 2016-07-01
3 2016-07-01 2016-08-01
4 2016-08-01 2016-09-01
5 2016-09-01 2016-10-01
6 2016-10-01 2016-11-01
7 2016-11-01 2016-12-01
8 2016-12-01 2017-01-01
9 2017-01-01 2017-02-01
10 2017-02-01 2017-03-01
11 2017-03-01 2017-04-01
12 2017-04-01 2017-05-01
13 2017-05-01 2017-06-01
14 2017-06-01 2017-07-01
15 2017-07-01 2017-08-01
16 2017-08-01 2017-09-01
17 2017-09-01 2017-10-01
18 2017-10-01 2017-11-01
19 2017-11-01 2017-12-01
20 2017-12-01 2018-01-01
21 2018-01-01 2018-02-01
22 2018-02-01 2018-03-01
23 2018-03-01 2018-04-01
24 2018-04-01 2018-05-01
25 2018-05-01 2018-06-01
26 2018-06-01 2018-07-01
27 2018-07-01 2018-08-01
28 2018-08-01 2018-09-01
29 2018-09-01 2018-10-01
30 2018-10-01 2018-11-01
31 2018-11-01 2018-12-01
32 2018-12-01 2019-01-01
33 2019-01-01 2019-02-01
34 2019-02-01 2019-03-01
35 2019-03-01 2019-04-01
2.5222244262695312


In [4]:
df.loc[(df.index >= "2016-04-01") & (df.index <= "2016-05-01")]

High         Low        Open       Close      Volume  \
Date                                                                     
2016-04-01  197.250000  192.000000  193.699997  195.649994  21752206.0   
2016-04-04  197.449997  192.550003  197.300003  194.699997  15732565.0   
2016-04-05  194.550003  183.300003  193.899994  184.350006  36635637.0   
2016-04-06  185.500000  182.199997  185.000000  183.850006  16350631.0   
2016-04-07  185.649994  181.000000  183.800003  181.949997  19430601.0   
2016-04-08  183.949997  180.199997  181.649994  183.100006  15805231.0   
2016-04-11  188.899994  182.000000  183.850006  188.250000  18990364.0   
2016-04-12  190.250000  186.300003  188.500000  187.800003  14563344.0   
2016-04-13  193.800003  190.800003  191.550003  191.899994  17573045.0   
2016-04-18  191.500000  185.600006  191.449997  186.750000  13985439.0   
2016-04-20  188.649994  184.100006  188.350006  187.300003  20163005.0   
2016-04-21  197.399994  190.000000  190.500000  194.350006  31008152.0   
2016-04-22  201.500000  191.550003  193.600006  200.149994  34049763.0   
2016-04-25  202.550003  195.800003  200.949997  197.050003  23835613.0   
2016-04-26  201.399994  194.550003  195.949997  200.949997  21809451.0   
2016-04-27  200.899994  195.500000  200.899994  196.149994  22801603.0   
2016-04-28  198.199997  191.199997  196.750000  192.050003  24555479.0   
2016-04-29  194.000000  186.449997  191.899994  189.000000  21021661.0   

             Adj Close  
Date                    
2016-04-01  191.382736  
2016-04-04  190.453461  
2016-04-05  180.329224  
2016-04-06  179.840118  
2016-04-07  177.981552  
2016-04-08  179.106476  
2016-04-11  184.144150  
2016-04-12  183.703964  
2016-04-13  187.714539  
2016-04-18  182.676865  
2016-04-20  183.214874  
2016-04-21  190.111115  
2016-04-22  195.784592  
2016-04-25  192.752213  
2016-04-26  196.567139  
2016-04-27  191.871841  
2016-04-28  187.861267  
2016-04-29  184.877792

#### Daily Average Return

In [5]:
start = "2016-04-01"
end = str(int(start[:4]) + 3) + start[4:]
print(start, end)
df = pdr.get_data_yahoo("HDFCBANK.BO", start = start, end = end)
df['DR'] = df['Close'] - df['Open']
avg = np.mean(df['DR'])
print(avg)

2016-04-01 2019-04-01
-0.30640044341216216


In [6]:
print(df.head(1))
print(df.tail(1))

             High    Low   Open  Close   Volume   Adj Close   DR
Date                                                            
2016-04-01  536.5  528.5  533.0  532.5  75410.0  512.739319 -0.5
                   High          Low    Open        Close     Volume  \
Date                                                                   
2019-04-01  1166.180054  1152.219971  1162.5  1155.030029  1049036.0   

              Adj Close        DR  
Date                               
2019-04-01  1145.349731 -7.469971  


In [7]:
df.head()

High         Low   Open       Close    Volume   Adj Close  \
Date                                                                          
2016-04-01  536.500000  528.500000  533.0  532.500000   75410.0  512.739319   
2016-04-04  536.224976  532.150024  534.5  534.650024   70052.0  514.809570   
2016-04-05  538.325012  527.625000  534.0  529.150024  158490.0  509.513580   
2016-04-06  533.400024  528.349976  532.5  530.750000   87236.0  511.054291   
2016-04-07  535.500000  523.599976  535.0  527.825012   79930.0  508.237762   

                  DR  
Date                  
2016-04-01 -0.500000  
2016-04-04  0.150024  
2016-04-05 -4.849976  
2016-04-06 -1.750000  
2016-04-07 -7.174988

In [8]:
start = "2016-04-01"
end = str(int(start[:4]) + 3) + start[4:]
all_stocks = []
positive_return = []
for i in range(len(syms)):
    try:
        a = pdr.get_data_yahoo(syms[i], start = start, end = end)
        all_stocks.append(a)
        a['Daily Return'] = (a['Close'] - a['Open'])
        avg = np.mean(a['Daily Return'])
        print(syms[i], avg)
        if avg > 0:
            positive_return.append(syms[i])
    except:
        print(f"error in {syms[i]}")
print(positive_return)

SBIN.NS -0.29972991943359373
AXISBANK.BO -0.4705414643158784
IOC.BO -0.4549079379519901
NMDC.BO -0.3495272249788851
KRITIIND.BO -0.1679729564769848
TATAPOWER.NS -0.1386483991468275
AUROLAB.BO -0.6180403554761732
RESONANCE.BO -0.32263512740264066
ANDHRAPET.BO -0.10843238443941683
MANALIPETC.BO -0.19081084534928605
GAIL.NS -0.2024765530148068
SAIL.NS -0.11635128742939717
HDFCBANK.BO -0.30640044341216216
ONGC.NS -0.41290528580949115
INFY.BO -0.5947298616976351
BHAGYAPROP.BO 0.0368735420390928
FEDERALBNK.NS -0.15094557581721124
WIPRO.BO -0.23393115481814822
IDEA.NS -0.12835879970241237
ALOKTEXT.BO -0.021040539644859933
BANKBARODA.BO -0.4215543695398279
BHEL.NS -0.17403141743428
DISHTV.BO -0.28695941873498865
VEDL.BO -0.2747294245539485
PTC.NS -0.14871617394524653
PRESSMN.NS -0.261351355990848
VEDL.BO -0.2747294245539485
['BHAGYAPROP.BO']


In [9]:
start = "2016-04-01"
end = str(int(start[:4]) + 3) + start[4:]
eq = []
avgs = []
for i in range(5):
    e = pdr.get_data_yahoo(syms[i], start = start, end = end)
    eq.append(e)
    e['Daily Return'] = e['Close'] - e['Open']
    avg = np.mean(e['Daily Return'])
    avgs.append(avg)

In [10]:
eq[0].head()

High         Low        Open       Close      Volume  \
Date                                                                     
2016-04-01  197.250000  192.000000  193.699997  195.649994  21752206.0   
2016-04-04  197.449997  192.550003  197.300003  194.699997  15732565.0   
2016-04-05  194.550003  183.300003  193.899994  184.350006  36635637.0   
2016-04-06  185.500000  182.199997  185.000000  183.850006  16350631.0   
2016-04-07  185.649994  181.000000  183.800003  181.949997  19430601.0   

             Adj Close  Daily Return  
Date                                  
2016-04-01  191.382736      1.949997  
2016-04-04  190.453461     -2.600006  
2016-04-05  180.329224     -9.549988  
2016-04-06  179.840118     -1.149994  
2016-04-07  177.981552     -1.850006

In [11]:
for e in eq:
    e['Daily Return'] = (e['Close'] - e['Open'])*100 / e['Open']

In [12]:
for e in eq:
    avg = np.mean(e['Daily Return'])
    e['Ret - avg'] = e['Daily Return'] - avg

In [13]:
m = eq[0].shape[0]
n = len(eq)
excess_return = np.zeros([m, n])
for i in range(n):
    excess_return[:, i] = eq[i]['Ret - avg']

In [14]:
X = excess_return
mat = np.dot(np.transpose(X), X)

In [15]:
vcm = mat / m

In [16]:
std = []
for e in eq:
    mean = np.mean(e['Daily Return'])
    m = e.shape[0]
    st = sqrt(np.sum((e['Daily Return'] - mean)**2) / m)
    std.append(st)
print(std)

[1.876151865979658, 1.7354930090540837, 1.8297082602550838, 1.8422035518432398, 3.851188770588137]


In [17]:
stds = np.array(std).reshape(-1, 1)
print(stds.shape)

(5, 1)


In [18]:
product_std = np.dot(stds, np.transpose(stds))
product_std.shape

(5, 5)

### Correlation
**corr = variance_covariance_matrix / product_of_sds**

In [19]:
corr = vcm / product_std
print(corr)

[[1.         0.39331504 0.18812314 0.30136006 0.12007307]
 [0.39331504 1.         0.17336731 0.1810741  0.07055679]
 [0.18812314 0.17336731 1.         0.23930562 0.0635524 ]
 [0.30136006 0.1810741  0.23930562 1.         0.14940654]
 [0.12007307 0.07055679 0.0635524  0.14940654 1.        ]]


In [20]:
weights = np.array([0.2, 0.2, 0.2, 0.2, 0.2]).reshape(-1, 1)
weights.shape

(5, 1)

In [21]:
weighted_sd = stds * weights
print(weighted_sd, stds)

[[0.37523037]
 [0.3470986 ]
 [0.36594165]
 [0.36844071]
 [0.77023775]] [[1.87615187]
 [1.73549301]
 [1.82970826]
 [1.84220355]
 [3.85118877]]


### Portfolio Variance
**Portfolio Variance = Sqrt (Transpose (Wt.SD) * Correlation Matrix * Wt. SD)**

In [22]:
portfolio_var = np.dot(np.dot(np.transpose(weighted_sd), corr), weighted_sd)
portfolio_var[0][0]

1.7442879620426066

In [23]:
final_pv = sqrt(portfolio_var[0][0])
final_pv

1.3207149435221086

### Maximizing Returns by fixing Portfolio Variance

#### Monte-Carlo Method: Using randomly generated weights

In [24]:
min_port_var = 1.20
max_port_var = 1.32
port_vars = []
returns = []
rand_wts = []
for i in range(0, 10000):
    random_weights = np.random.dirichlet(np.ones(5), size = 1).T
    random_weighted_sd = stds * random_weights
    portfolio_var = sqrt(np.sum(np.dot(np.dot(np.transpose(random_weighted_sd), corr), random_weighted_sd)))
    if (portfolio_var >= min_port_var) & (portfolio_var <= max_port_var):
        port_vars.append(portfolio_var)
        rand_wts.append(random_weights)
        total_return = np.sum(avgs * random_weights)
        returns.append(total_return)
#print(len(returns), len(port_vars), len(rand_wts))
max_index = returns.index(max(returns))
max_return = returns[max_index]
best_wts = rand_wts[max_index]
min_var = port_vars[max_index]
print(f"Best Return: {max_return}, Best Weights: {best_wts}, Minimum Portfolio Variance: {min_var}, Sum of weights: {np.sum(best_wts)}")
print(f"Worst Return: {min(returns)}")

Best Return: -1.7426795031573312, Best Weights: [[0.37426846]
 [0.23406933]
 [0.10644216]
 [0.15911911]
 [0.12610094]], Minimum Portfolio Variance: 1.296089179088856, Sum of weights: 0.9999999999999997
Worst Return: -1.7426795031573328


### Minimizing Portfolio Variance

#### Monte-Carlo Method: Using randomly generated weights

In [25]:
port_vars = []
rand_wts = []
for i in range(0, 10000):
    random_weights = np.random.dirichlet(np.ones(5), size = 1).T
    rand_wts.append(random_weights)
    random_weighted_sd = stds * random_weights
    portfolio_var = sqrt(np.sum(np.dot(np.dot(np.transpose(random_weighted_sd), corr), random_weighted_sd)))
    port_vars.append(portfolio_var)
min_index = port_vars.index(min(port_vars))
best_wts = rand_wts[min_index]
min_var = port_vars[min_index]
print(f"Best Weights: {best_wts}, Minimum Portfolio Variance: {min_var}, Sum of weights: {np.sum(best_wts)}")

Best Weights: [[0.15849709]
 [0.29542793]
 [0.28232342]
 [0.21522924]
 [0.04852232]], Minimum Portfolio Variance: 1.1763584975054986, Sum of weights: 0.9999999999999998


### Maximizing Sharpe Ratio

#### Monte-Carlo Method: Using randomly generated weights

In [26]:
start = "2016-04-01"
end = str(int(start[:4]) + 1) + start[4:]
e = pdr.get_data_yahoo("SBIN.NS", start = start, end = "2019-04-01")
e['Daily Return'] = 0
sliced_data = e.loc[(e.index >= start) & (e.index <= end)]
year_avg = (sliced_data.iloc[-1]['Close'] - sliced_data.iloc[0]['Open'])*100 / sliced_data.iloc[0]['Open']
e.loc[sliced_data.index, 'Daily Return'] = year_avg
print(year_avg)
e.loc[sliced_data.index]['Daily Return']

51.47134667992929


Date
2016-04-01    51.471347
2016-04-04    51.471347
2016-04-05    51.471347
2016-04-06    51.471347
2016-04-07    51.471347
                ...    
2017-03-27    51.471347
2017-03-28    51.471347
2017-03-29    51.471347
2017-03-30    51.471347
2017-03-31    51.471347
Name: Daily Return, Length: 247, dtype: float64

In [27]:
eq = []
avgs = []
for i in range(5):
    start = "2016-04-01"
    end = str(int(start[:4]) + 3) + start[4:]
    e = pdr.get_data_yahoo(syms[i], start = start, end = end)
    eq.append(e)
    e['Daily Return'] = 0
    start = "2016-04-01"
    #e['Daily Return'] = (e['Close'] - e['Open'])*100 / e['Open']
    for j in range(3):
        end = str(int(start[:4]) + 1) + start[4:]
        sliced_data = e.loc[(e.index >= start) & (e.index <= end)]
        year_avg = (sliced_data.iloc[-1]['Close'] - sliced_data.iloc[0]['Open'])*100 / sliced_data.iloc[0]['Open']
        e.loc[sliced_data.index, 'Daily Return'] = year_avg
        start = end
        #print(e.loc[sliced_data.index, 'Daily Return'].tail(2))

#### Yearly Average Return

In [28]:
avg_return = []
for e in eq:
    ret = 0
    start = "2016-04-01"
    for i in range(3):
        end = str(int(start[:4]) + 1) + start[4:]
        sliced_data = e.loc[(e.index >= start) & (e.index <= end)]
        ret += (sliced_data.iloc[-1]['Close'] - sliced_data.iloc[0]['Open']) / sliced_data.iloc[0]['Open']
        start = end
    avg_return.append(ret*100/3)
yearly_avg_return = np.array(avg_return).reshape(-1, 1)
print(yearly_avg_return.shape, yearly_avg_return)

(5, 1) [[21.47260214]
 [21.24438064]
 [25.80360703]
 [ 3.5706382 ]
 [ 3.54023575]]


In [29]:
random_weights = np.random.dirichlet(np.ones(5), size = 1).T
excess_ret = yearly_avg_return * random_weights
print(random_weights)
print(excess_ret)
print(np.sum(excess_ret))

[[0.58284934]
 [0.21566999]
 [0.09376074]
 [0.03197725]
 [0.07574268]]
[[12.51529202]
 [ 4.58177546]
 [ 2.4193652 ]
 [ 0.11417919]
 [ 0.26814694]]
19.898758807328445


In [30]:
count = 0
for e in eq:
    e['Ret - avg'] = e['Daily Return'] - yearly_avg_return[count]
    count += 1

In [31]:
m = eq[0].shape[0]
n = len(eq)
excess_return = np.zeros([m, n])
for i in range(n):
    excess_return[:, i] = eq[i]['Ret - avg']

In [32]:
X = excess_return
mat = np.dot(np.transpose(X), X)

In [33]:
vcm = mat / m

In [34]:
std = []
count = 0
for e in eq:
    mean = yearly_avg_return[count]
    m = e.shape[0]
    st = sqrt(np.sum((e['Daily Return'] - mean)**2) / m)
    std.append(st)
    count += 1
print(std)

[27.62632166327554, 20.716227675044177, 50.05913640711804, 20.934839927246518, 37.22752483268484]


In [35]:
stds = np.array(std).reshape(-1, 1)
print(stds.shape)

(5, 1)


In [36]:
product_std = np.dot(stds, np.transpose(stds))
product_std.shape

(5, 5)

### Correlation
**corr = variance_covariance_matrix / product_of_sds**

In [37]:
corr = vcm / product_std
print(corr)

[[ 1.          0.31835789  0.76057095  0.76473878 -0.08952942]
 [ 0.31835789  1.         -0.37334073 -0.36735516 -0.97266612]
 [ 0.76057095 -0.37334073  1.          0.99997924  0.57855406]
 [ 0.76473878 -0.36735516  0.99997924  1.          0.57328625]
 [-0.08952942 -0.97266612  0.57855406  0.57328625  1.        ]]


In [38]:
srs = []
portfolio_vars = []
rand_wts = []
portfolio_return = []
risk_free_rate = 4
for i in range(0, 10000):
    random_weights = np.random.dirichlet(np.ones(5), size = 1).T
    rand_wts.append(random_weights)
    random_weighted_sd = stds * random_weights
    portfolio_std = np.sum(np.dot(np.dot(np.transpose(random_weighted_sd), corr), random_weighted_sd))
    portfolio_vars.append(sqrt(portfolio_std))
    excess_return = np.sum(yearly_avg_return * random_weights)
    portfolio_return.append(excess_return)
    sharpe_ratio = (excess_return - risk_free_rate) / portfolio_std
    srs.append(sharpe_ratio)
max_index = srs.index(max(srs))
best_wts = rand_wts[max_index]
max_sr = srs[max_index]
portfolio_var = portfolio_vars[max_index]
max_return = portfolio_return[max_index]
print(f"Max Sharpe Ratio: {max_sr}")
print(f"Best Weights: {best_wts}")
print(f"Portfolio Variance: {portfolio_var}, Sum of weights: {np.sum(best_wts)}")
print(f"Max Return: {max_return}")

Max Sharpe Ratio: 0.5591199944594113
Best Weights: [[0.01197538]
 [0.5982698 ]
 [0.01114419]
 [0.00665209]
 [0.37195854]]
Portfolio Variance: 4.353123522044135, Sum of weights: 1.0
Max Return: 14.595147435714605
