In [1]:
import numpy as np
import yfinance as yf
from math import sqrt
from pandas_datareader import data as pdr

In [2]:
eq = []
syms = ['SBIN.NS', 'AXISBANK.BO', 'IOC.BO', 'NMDC.BO', 'KRITIIND.BO']
for i in range(5):
    eq.append(pdr.get_data_yahoo(syms[i], start = '2016-07-02', end = '2019-07-02'))

In [3]:
eq[0].head()

High         Low        Open       Close      Volume  \
Date                                                                     
2016-07-04  224.350006  222.000000  222.350006  223.000000  16534518.0   
2016-07-05  225.149994  221.550003  223.250000  223.500000  15357018.0   
2016-07-07  224.600006  219.350006  223.899994  220.050003  12917872.0   
2016-07-08  220.850006  216.500000  220.149994  218.300003  16017389.0   
2016-07-11  225.449997  222.000000  223.600006  224.699997  15831791.0   

             Adj Close  
Date                    
2016-07-04  221.001373  
2016-07-05  221.496887  
2016-07-07  218.077820  
2016-07-08  216.343506  
2016-07-11  222.686127

In [4]:
for e in eq:
    e['Daily Return'] = (e['Close'] - e['Open'])*100 / e['Open']
    print(e['Daily Return'].head())

Date
2016-07-04    0.292329
2016-07-05    0.111982
2016-07-07   -1.719514
2016-07-08   -0.840332
2016-07-11    0.491946
Name: Daily Return, dtype: float64
Date
2016-07-04   -0.384611
2016-07-05   -0.350882
2016-07-07    0.509542
2016-07-08    1.007396
2016-07-11   -1.117171
Name: Daily Return, dtype: float64
Date
2016-07-04    1.064980
2016-07-05   -0.645835
2016-07-07   -0.796643
2016-07-08   -0.594477
2016-07-11    1.335736
Name: Daily Return, dtype: float64
Date
2016-07-04    0.105931
2016-07-05    0.685648
2016-07-07   -0.312503
2016-07-08   -1.662336
2016-07-11    0.996849
Name: Daily Return, dtype: float64
Date
2016-07-04    0.952381
2016-07-05   -1.824818
2016-07-07    2.416355
2016-07-08   -6.055044
2016-07-11    5.928854
Name: Daily Return, dtype: float64


In [5]:
for e in eq:
    avg = np.mean(e['Daily Return'])
    e['Ret - avg'] = e['Daily Return'] - avg
    print(e['Ret - avg'].head())

Date
2016-07-04    0.391711
2016-07-05    0.211364
2016-07-07   -1.620132
2016-07-08   -0.740950
2016-07-11    0.591328
Name: Ret - avg, dtype: float64
Date
2016-07-04   -0.275739
2016-07-05   -0.242010
2016-07-07    0.618414
2016-07-08    1.116268
2016-07-11   -1.008299
Name: Ret - avg, dtype: float64
Date
2016-07-04    1.326703
2016-07-05   -0.384112
2016-07-07   -0.534920
2016-07-08   -0.332754
2016-07-11    1.597459
Name: Ret - avg, dtype: float64
Date
2016-07-04    0.366216
2016-07-05    0.945933
2016-07-07   -0.052217
2016-07-08   -1.402050
2016-07-11    1.257135
Name: Ret - avg, dtype: float64
Date
2016-07-04    1.364777
2016-07-05   -1.412421
2016-07-07    2.828752
2016-07-08   -5.642648
2016-07-11    6.341250
Name: Ret - avg, dtype: float64


In [6]:
m = eq[0].shape[0]
n = len(eq)
excess_return = np.zeros([m, n])
for i in range(n):
    excess_return[:, i] = eq[i]['Ret - avg']
excess_return[:5]

array([[ 0.39171124, -0.27573936,  1.3267027 ,  0.36621646,  1.36477703],
       [ 0.21136417, -0.24201015, -0.38411168,  0.94593342, -1.41242147],
       [-1.62013151,  0.61841388, -0.53492022, -0.05221731,  2.82875157],
       [-0.74094991,  1.11626752, -0.33275431, -1.4020502 , -5.6426484 ],
       [ 0.59132789, -1.0082991 ,  1.59745941,  1.25713469,  6.34125001]])

In [7]:
X = excess_return
mat = np.dot(np.transpose(X), X)
mat[:5]

array([[ 2416.06861144,   937.61563418,   494.3344682 ,   731.92591291,
          610.56427023],
       [  937.61563418,  2180.14029773,   438.07725962,   463.2781788 ,
          258.99365099],
       [  494.3344682 ,   438.07725962,  2515.93900851,   610.90168995,
          326.50164511],
       [  731.92591291,   463.2781788 ,   610.90168995,  2471.90168032,
          721.04214973],
       [  610.56427023,   258.99365099,   326.50164511,   721.04214973,
        10151.26913492]])

In [8]:
vcm = mat / m
vcm[:5]

array([[ 3.27380571,  1.27048189,  0.6698299 ,  0.99176953,  0.82732286],
       [ 1.27048189,  2.95411964,  0.59360062,  0.62774821,  0.35093991],
       [ 0.6698299 ,  0.59360062,  3.40913145,  0.82778007,  0.44241415],
       [ 0.99176953,  0.62774821,  0.82778007,  3.34946027,  0.97702188],
       [ 0.82732286,  0.35093991,  0.44241415,  0.97702188, 13.75510723]])

In [9]:
std = []
for e in eq:
    mean = np.mean(e['Daily Return'])
    m = e.shape[0]
    st = sqrt(np.sum((e['Daily Return'] - mean)**2) / m)
    std.append(st)
print(std)

[1.809366106279542, 1.718755260244544, 1.8463833426041016, 1.8301530732265505, 3.708787838215061]


In [10]:
stds = np.array(std).reshape(-1, 1)

In [11]:
product_std = np.dot(stds, np.transpose(stds))
product_std.shape

(5, 5)

### Correlation
**corr = variance_covariance_matrix / product_of_sds**

In [12]:
corr = vcm / product_std
print(corr)

[[1.         0.40853379 0.20050085 0.29950005 0.1232868 ]
 [0.40853379 1.         0.18705031 0.19956484 0.05505373]
 [0.20050085 0.18705031 1.         0.24496592 0.06460634]
 [0.29950005 0.19956484 0.24496592 1.         0.14394112]
 [0.1232868  0.05505373 0.06460634 0.14394112 1.        ]]


In [13]:
weights = np.array([0.2, 0.2, 0.2, 0.2, 0.2]).reshape(-1, 1)
weights.shape

(5, 1)

In [14]:
weighted_sd = stds * 0.2
print(weighted_sd, stds)

[[0.36187322]
 [0.34375105]
 [0.36927667]
 [0.36603061]
 [0.74175757]] [[1.80936611]
 [1.71875526]
 [1.84638334]
 [1.83015307]
 [3.70878784]]


### Portfolio Variance
**Portfolio Variance = Sqrt (Transpose (Wt.SD) * Correlation Matrix * Wt. SD)**

In [15]:
portfolio_var = np.dot(np.dot(np.transpose(weighted_sd), corr), weighted_sd)
portfolio_var[0][0]

1.6759776938960191

In [16]:
final_pv = sqrt(portfolio_var[0][0])
final_pv

1.2945955715573954

### Minimizing Portfolio Variance

In [17]:
from scipy.optimize import minimize

In [18]:
def portfolio_variance(weights, stds, corr):
    weighted_sd = weights * stds
    k = np.dot(np.transpose(weighted_sd), corr)
    ans = np.dot(k, weighted_sd)[0][0]
    return sqrt(ans)

In [19]:
cons = ({'type': 'eq', 'fun': lambda x: np.sum(x) - 1})
bnds = ((0.001, 1), (0.001, 1), (0.001, 1), (0.001, 1), (0.001, 1))

In [20]:
minimize(portfolio_variance, [0.3, 0.3, 0.2, 0.1, 0.1], args = (stds, corr),
         method = "SLSQP", constraints = cons, bounds = bnds)

     fun: 0.006472977858323092
     jac: array([6.47297786, 0.        , 0.        , 0.        , 0.        ])
 message: 'Optimization terminated successfully.'
    nfev: 14
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.001  , 0.37475, 0.27475, 0.17475, 0.17475])

In [21]:
min_op = minimize(portfolio_variance, [0.3, 0.3, 0.2, 0.1, 0.1], args = (stds, corr),
         method = "SLSQP", constraints = cons, bounds = bnds)

In [22]:
best_weights = min_op.x.reshape(-1, 1)

In [23]:
min_variance = min_op.fun

In [24]:
print(f"Best Weights to achieve minimum portfolio variance: {best_weights}")
print(f"Minimum value of porfolio variance: {float(min_variance)}")

Best Weights to achieve minimum portfolio variance: [[0.001  ]
 [0.37475]
 [0.27475]
 [0.17475]
 [0.17475]]
Minimum value of porfolio variance: 0.006472977858323092


In [25]:
print(np.sum(best_weights))

1.0


In [26]:
portfolio_variance([0.3, 0.3, 0.2, 0.1, 0.1], stds, corr)

1.9418933573360928

In [27]:
portfolio_variance(best_weights, stds, corr)

1.276154732833452

In [28]:
min_op = minimize(portfolio_variance, [0.2, 0.2, 0.2, 0.2, 0.2], args = (stds, corr),
         method = "SLSQP", constraints = cons, bounds = bnds)

In [29]:
best_weights = min_op.x.reshape(-1, 1)

In [30]:
min_variance = min_op.fun

In [31]:
print(f"Best Weights to achieve minimum portfolio variance: {best_weights}")
print(f"Minimum value of porfolio variance: {float(min_variance)}")

Best Weights to achieve minimum portfolio variance: [[0.001  ]
 [0.24975]
 [0.24975]
 [0.24975]
 [0.24975]]
Minimum value of porfolio variance: 0.0064729778577869825


In [32]:
print(np.sum(best_weights))

1.0000000000000246


In [33]:
portfolio_variance([0.2, 0.2, 0.2, 0.2, 0.2], stds, corr)

1.2945955715573954

In [34]:
portfolio_variance(best_weights, stds, corr)

1.393618116369442